In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

In [3]:
base_rate = pd.read_csv("C:/Users/SesacPython/Desktop/dataset/금리예측프로젝트/base_rate.csv")

# confusion matrix
# cm1 - 뉴스 기준
# cm2 - 의사록 기준
y_true = list(base_rate.polarity)
y_pred_by_news = list(base_rate.pred)
y_pred_by_mpc = list(base_rate.mpc_pol_pred)
cm1 = confusion_matrix(y_true, y_pred_by_news)
cm2 = confusion_matrix(y_true, y_pred_by_mpc)

In [4]:
cm1

array([[70, 64, 26],
       [ 0, 25,  0],
       [ 1,  0, 16]], dtype=int64)

In [4]:
cm2

array([[61, 77, 22],
       [ 4, 21,  0],
       [ 9,  0,  8]], dtype=int64)

In [13]:
# accuracy, precision, recall, f1 score 계산
cm1_accuracy = sum([cm1[i][i] for i in range(3)]) / sum(sum(cm1))
cm2_accuracy = sum([cm2[i][i] for i in range(3)]) / sum(sum(cm2))

cm1_precision_0 = cm1[0][0] / sum([cm1[i][0] for i in range(3)])
cm1_precision_1 = cm1[1][1] / sum([cm1[i][1] for i in range(3)])
cm1_precision_2 = cm1[2][2] / sum([cm1[i][2] for i in range(3)])


cm2_precision_0 = cm2[0][0] / sum([cm2[i][0] for i in range(3)])
cm2_precision_1 = cm2[1][1] / sum([cm2[i][1] for i in range(3)])
cm2_precision_2 = cm2[2][2] / sum([cm2[i][2] for i in range(3)])


cm1_recall_0 = cm1[0][0] / sum(cm1[0])
cm1_recall_1 = cm1[1][1] / sum(cm1[1])
cm1_recall_2 = cm1[2][2] / sum(cm1[2])


cm2_recall_0 = cm2[0][0] / sum(cm2[0])
cm2_recall_1 = cm2[1][1] / sum(cm2[1])
cm2_recall_2 = cm2[2][2] / sum(cm2[2])

cm1_f1_0 = 2*cm1_precision_0*cm1_recall_0 / (cm1_precision_0 + cm1_recall_0)
cm1_f1_1 = 2*cm1_precision_1*cm1_recall_1 / (cm1_precision_1 + cm1_recall_1)
cm1_f1_2 = 2*cm1_precision_2*cm1_recall_2 / (cm1_precision_2 + cm1_recall_2)

cm2_f1_0 = 2*cm2_precision_0*cm2_recall_0 / (cm2_precision_0 + cm2_recall_0)
cm2_f1_1 = 2*cm2_precision_1*cm2_recall_1 / (cm2_precision_1 + cm2_recall_1)
cm2_f1_2 = 2*cm2_precision_2*cm2_recall_2 / (cm2_precision_2 + cm2_recall_2)

In [8]:
cm1

array([[70, 64, 26],
       [ 0, 25,  0],
       [ 1,  0, 16]], dtype=int64)

In [12]:
cm1_f1_0, cm1_f1_1, cm1_f1_2

(0.6060606060606061, 0.4385964912280702, 0.5423728813559321)

In [14]:
# sklearn 비교(cm1)
from sklearn.metrics import classification_report
print(classification_report(y_true, y_pred_by_news))

              precision    recall  f1-score   support

           0       0.99      0.44      0.61       160
           1       0.28      1.00      0.44        25
           2       0.38      0.94      0.54        17

    accuracy                           0.55       202
   macro avg       0.55      0.79      0.53       202
weighted avg       0.85      0.55      0.58       202



In [15]:
li_0 = cm1_precision_0, cm1_recall_0, cm1_f1_0
li_1 = cm1_precision_1, cm1_recall_1, cm1_f1_1
li_2 = cm1_precision_2, cm1_recall_2, cm1_f1_2

In [16]:
print(li_0)
print(li_1)
print(li_2)
print(cm1_accuracy)

(0.9859154929577465, 0.4375, 0.6060606060606061)
(0.2808988764044944, 1.0, 0.4385964912280702)
(0.38095238095238093, 0.9411764705882353, 0.5423728813559321)
0.5495049504950495


In [17]:
# sklearn 비교(cm2)
from sklearn.metrics import classification_report
print(classification_report(y_true, y_pred_by_mpc))

              precision    recall  f1-score   support

           0       0.82      0.38      0.52       160
           1       0.21      0.84      0.34        25
           2       0.27      0.47      0.34        17

    accuracy                           0.45       202
   macro avg       0.44      0.56      0.40       202
weighted avg       0.70      0.45      0.48       202



In [18]:
cm2_li_0 = cm2_precision_0, cm2_recall_0, cm2_f1_0
cm2_li_1 = cm2_precision_1, cm2_recall_1, cm2_f1_1
cm2_li_2 = cm2_precision_2, cm2_recall_2, cm2_f1_2

In [19]:
print(cm2_li_0)
print(cm2_li_1)
print(cm2_li_2)
print(cm2_accuracy)

(0.8243243243243243, 0.38125, 0.5213675213675214)
(0.21428571428571427, 0.84, 0.3414634146341463)
(0.26666666666666666, 0.47058823529411764, 0.3404255319148936)
0.44554455445544555
